= Simple Route Rules
include::_attributes.adoc[]

Send several requests to the customer ingress and watch their responses:

[source, bash]
https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/scripts/run.sh
----
./scripts/run.sh  
----

The default Kubernetes/OpenShift behavior is to round-robin load-balance across all available pods behind a single Service. Add another replica of recommendation-v2 Deployment and observe the result:

[source,bash]
----
oc scale --replicas=2 deployment/recommendation-v2 
or
kubectl scale --replicas=2 deployment/recommendation-v2 
----

Now, you will see two requests into the v2 and one for v1.

[source,bash]
----
customer => preference => recommendation v1 from '2819441432-qsp25': 29
customer => preference => recommendation v2 from '99634814-sf4cl': 37
customer => preference => recommendation v2 from '99634814-sf4cl': 38
----

Scale back to a single replica of the recommendation-v2 Deployment

[source,bash]
----
oc scale --replicas=1 deployment/recommendation-v2 
or
kubectl scale --replicas=1 deployment/recommendation-v2 
----

[#istiorouting]
== Changing Istio Routings

[#alltorecommendationv1]
=== All users to recommendation:v1

First create a destination rule: 
[source,bash,subs="+macros,+attributes"]
----
oc create -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/destination-rule-recommendation-v1-v2.yml
----

then create a virtual service:
----
oc create -f  https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-recommendation-v1.yml
----

Generate some traffic.
you should only see recommendation v1 being called.

Ok, so what just happened ? 
North/south inbound traffic goes into the istio Gateway to enter the service mesh.

The Virtual Service defines a set of traffic routing rules to apply when a host is addressed.

----
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommendation
spec:
  hosts:
  - recommendation
  http:
  - route:
    - destination:
        host: recommendation
        subset: version-v1
      weight: 100
---
----

In our example, weight based traffic rules is used and all traffic is send to the pod matching version-v1

----
oc get pods -L version
----

A Destination Rule defines policies that are applied to the traffic intended for a service after routing has occurred

----
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  creationTimestamp: null
  name: recommendation
spec:
  host: recommendation
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - labels:
      version: v1
    name: version-v1
  - labels:
      version: v2
    name: version-v2
---
----

The Service Mesh installed in the lab is using mTLS traffic, we define a DestinationRule to encrypt traffic using 2-way SSL. Otherwise, routing will failed.


[#alltorecommendationv1v2]
=== All users to recommendation v1 and v2

By simply removing the rule

[source,bash]
----

oc delete -f  https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-recommendation-v1.yml
----

and you should see the default behavior of load-balancing between v1 and v2



[#canarydeploymentrecommendation]
=== Canary deployment: Split traffic between v1 and v2

Canary Deployment scenario: push v2 into the cluster but slowly send end-user traffic to it, if you continue to see success, continue shifting more traffic over time

[source,bash]
----
oc get pods -l app=recommendation
or
kubectl get pods -l app=recommendation 

NAME                                  READY     STATUS    RESTARTS   AGE
recommendation-v1-3719512284-7mlzw   2/2       Running   6          2h
recommendation-v2-2815683430-vn77w   2/2       Running   0          1h
----

Create the `virtualservice` that will send 90% of requests to v1 and 10% to v2

[source,bash,subs="+macros,+attributes"]
----
oc create -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-recommendation-v1_and_v2_90_10.yml
----

and send in several requests:

[source, bash]
----
./scripts/run.sh
----

In another terminal, change the mixture to be 75/25

[source,bash,subs="+macros,+attributes"]
----
oc replace -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-recommendation-v1_and_v2_75_25.yml
----

Clean up

[source,bash]
----
oc delete -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-recommendation-v1_and_v2_75_25.yml

oc delete -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/destination-rule-recommendation-v1-v2.yml
----

