= Advanced Route Rules
include::_attributes.adoc[]

[IMPORTANT]
.Before Start
====
You should have NO virtualservice nor destinationrule (in your namespace) `oc get virtualservice` `oc get destinationrule` 

====

[#canarydeploymentuseragent]
== Smart routing based on user-agent header (Canary Deployment)

What is your user-agent?

https://www.whoishostingthis.com/tools/user-agent/[https://www.whoishostingthis.com/tools/user-agent/]

Note: the "user-agent" header is added to OpenTracing baggage in the Customer service. From
there it is automatically propagated to all downstream services. To enable automatic
baggage propagation all intermediate services have to be instrumented with OpenTracing.
The baggage header for user agent has following form `baggage-user-agent: <value>`.

[#alltorecommendationv1]
=== Set recommendation to all v1

[source,bash,subs="+macros,+attributes"]
----
oc create -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/destination-rule-recommendation-v1-v2.yml

oc create -f  https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-recommendation-v1.yml
----

[#chrometov2]
=== Set Chrome users to v2

[source,bash,subs="+macros,+attributes"]
----
oc replace -f  https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-chrome-recommendation-v2.yml

oc get virtualservice -n tutorial
----

and test with a Chrome browser. You should see only v2 responses from recommendation.

and test with a Firefox browser, it should only see v1 responses from recommendation.


[source,bash]
----
to get the URL:
echo $CUSTOMER_URL
----


You can also attempt to use the curl -A command to test with different user-agent strings. 

[source,bash]
----
curl -A Chrome $CUSTOMER_URL
curl -A Firefox $CUSTOMER_URL
----

You can describe the virtualservice to see its configuration

[source,bash]
----
oc get virtualservice -o yaml 
----

==== Remove the Chrome rule

[source,bash]
----
oc delete -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-chrome-recommendation-v2.yml
----

[#mobiletov2]
=== Set mobile users to v2

[source,bash,subs="+macros,+attributes"]
----
oc create -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-mobile-recommendation-v2.yml

curl -A "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4(KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5" $CUSTOMER_URL

or navigate to $CUSTOMER_URL on your mobile device.
----

==== Clean up

[source,bash]
----
oc delete -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/destination-rule-recommendation-v1-v2.yml

oc delete -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-recommendation-v1.yml
----

or you can run:

[#mirroringtraffic]
== Mirroring Traffic (Dark Launch)

[source,bash]
----
oc get pods -l app=recommendation 
or 
kubectl get pods -l app=recommendation 
----

You should have 2 pods for recommendation based on the steps above

[source,bash]
----
oc get virtualservice 
oc get destinationrule
----

You should have NO virtualservice nor destinationrule (in `your` namespace) `oc get virtualservice` `oc get destinationrule` 

Create traffic mirroring rules (dark launch)

[source,bash,subs="+macros,+attributes"]
----
oc create -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/destination-rule-recommendation-v1-v2.yml
oc create -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-recommendation-v1-mirror-v2.yml 

curl $CUSTOMER_URL
----

Check the logs of recommendation-v2

[source,bash]
----
oc logs -f `oc get pods|grep recommendation-v2|awk '{ print $1 }'` -c recommendation
----

As you should be able to see, the requests to the $CUSTOMER_URL are returning v1, but from the log files, v2 is also called. This is known as Dark Launches, traffic is reaching your new version, but results comes from v1.

Clean up

[source,bash]
----
oc delete -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/destination-rule-recommendation-v1-v2.yml
oc delete -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/virtual-service-recommendation-v1-mirror-v2.yml 
----

[#accesscontrol]
== Access Control

IMPORTANT: The Access Control rules take some time to be applied and reflected. Be patient here!

[#whitelist]
=== Whitelist

We'll create a whitelist on the preference service to only allow requests from the recommendation service, which will make the preference service invisible to the customer service. Requests from the customer service to the preference service will return a 404 Not Found HTTP error code.

[source,bash,subs="+macros,+attributes"]
----
oc create -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/acl-whitelist.yml
----

[source,bash]
----
curl $CUSTOMER_URL
customer => 404 NOT_FOUND:preferencewhitelist.listchecker.tutorial:customer is not whitelisted
----

==== Clean up

[source,bash]
----
oc delete -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/acl-whitelist.yml
----



[#loadbalancer]
== Load Balancer

By default, you will see "round-robin" style load-balancing, but you can change it up, with the RANDOM option being fairly visible to the naked eye.

Add another v2 pod to the mix

[source,bash]
----
oc scale deployment recommendation-v2 --replicas=2 
or
kubectl scale deployment recommendation-v2 --replicas=2 
----

Wait a bit (oc get pods -w to watch)
and curl the customer endpoint many times

[source,bash]
----
curl $CUSTOMER_URL
----

Add a 3rd v2 pod to the mix

[source,bash]
----
$ oc scale deployment recommendation-v2 --replicas=3 
$ oc get pods 



NAME                                  READY     STATUS    RESTARTS   AGE
customer-1755156816-cjd2z             2/2       Running   0          1h
preference-3336288630-2cc6f          2/2       Running   0          1h
recommendation-v1-3719512284-bn42p   2/2       Running   0          59m
recommendation-v2-2815683430-97nnf   2/2       Running   0          43m
recommendation-v2-2815683430-d49n6   2/2       Running   0          51m
recommendation-v2-2815683430-tptf2   2/2       Running   0          33m
----

Wait for those 2/2 (two containers in each pod) and then poll the customer endpoint:

[source, bash]
----
curl $CUSTOMER_URL

or - if you downloaded the script:

./scripts/run.sh
----

The results should follow a fairly normal round-robin distribution pattern

[source,bash]
----
customer => preference => recommendation v1 from '99634814-d2z2t': 1145
customer => preference => recommendation v2 from '2819441432-525lh': 1
customer => preference => recommendation v2 from '2819441432-rg45q': 2
customer => preference => recommendation v2 from '2819441432-bs5ck': 181
customer => preference => recommendation v1 from '99634814-d2z2t': 1146
customer => preference => recommendation v2 from '2819441432-rg45q': 3
customer => preference => recommendation v2 from '2819441432-rg45q': 4
customer => preference => recommendation v2 from '2819441432-bs5ck': 182
----

Now, add the Random LB DestinationPolicy

[source,bash,subs="+macros,+attributes"]
----
oc create -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/destination-rule-recommendation_lb_policy_app.yml
----

And you should see a different pattern of which pod is being selected

[source,bash]
----
customer => preference => recommendation v2 from '2819441432-rg45q': 10
customer => preference => recommendation v2 from '2819441432-525lh': 3
customer => preference => recommendation v2 from '2819441432-rg45q': 11
customer => preference => recommendation v1 from '99634814-d2z2t': 1153
customer => preference => recommendation v1 from '99634814-d2z2t': 1154
customer => preference => recommendation v1 from '99634814-d2z2t': 1155
customer => preference => recommendation v2 from '2819441432-rg45q': 12
customer => preference => recommendation v2 from '2819441432-525lh': 4
customer => preference => recommendation v2 from '2819441432-525lh': 5
customer => preference => recommendation v2 from '2819441432-rg45q': 13
customer => preference => recommendation v2 from '2819441432-rg45q': 14
----

Clean up

[source,bash]
----
oc delete -f  https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/destination-rule-recommendation_lb_policy_app.yml

oc create -f https://raw.githubusercontent.com/redhat-canada/istio-tutorial/master/istiofiles/destination-rule-recommendation-v1-v2.yml

oc scale deployment recommendation-v2 --replicas=1 
----

[#ratelimiting]
== Rate Limiting

This section will be done as a DEMO, modifications to the istio Mixer are needed. 

IMPORTANT: The Rate Limiting rules take some time to be applied and reflected. Be patient here!

Here we will limit the number of concurrent requests into recommendation v2

For this DEMO , we will apply a rate limit handler

[source,bash,subs="+macros,+attributes"]
----
oc create -f recommendation_rate_limit_handler.yml
----

Now setup the requestcount quota

[source,bash,subs="+macros,+attributes"]
----
oc create -f rate_limit_rule.yml
----

Throw some requests at customer:

[source, bash]
----
./scripts/run.sh
----

You should see some 429 errors:

[source,bash]
----
customer => preference => recommendation v2 from '2819441432-f4ls5': 108
customer => preference => recommendation v1 from '99634814-d2z2t': 1932
customer => preference => recommendation v2 from '2819441432-f4ls5': 109
customer => preference => recommendation v1 from '99634814-d2z2t': 1933
customer => 503 preference => 429 RESOURCE_EXHAUSTED:Quota is exhausted for: RequestCount
customer => preference => recommendation v1 from '99634814-d2z2t': 1934
customer => preference => recommendation v2 from '2819441432-f4ls5': 110
customer => preference => recommendation v1 from '99634814-d2z2t': 1935
customer => 503 preference => 429 RESOURCE_EXHAUSTED:Quota is exhausted for: RequestCount
customer => preference => recommendation v1 from '99634814-d2z2t': 1936
customer => preference => recommendation v2 from '2819441432-f4ls5': 111
customer => preference => recommendation v1 from '99634814-d2z2t': 1937
customer => 503 preference => 429 RESOURCE_EXHAUSTED:Quota is exhausted for: RequestCount
customer => preference => recommendation v1 from '99634814-d2z2t': 1938
customer => preference => recommendation v2 from '2819441432-f4ls5': 112
----

DEMO Clean up

[source,bash]
----
oc delete -f rate_limit_rule.yml

oc delete -f recommendation_rate_limit_handler.yml
----

or you can run:

[source, bash]
----
./scripts/clean.sh
----