= Egress
include::_attributes.adoc[]

Let's see an example of using egress route by deploying a recommendation:v3 version. Egress service entry allow you to apply rules to how internal services interact with external APIs/services.

In this case, we are going to configure Istio to access http://now.httpbin.org from internal service (recommendation:v3).

[IMPORTANT]
.Before Start
====
You should have NO virtualservice nor destinationrule (in `tutorial` namespace) `oc get virtualservice` `oc get destinationrule` 
if so run:
====

[#createrecommendationv3]
== Create recommendation:v3

Deploy the recommendation v3 

----
oc create -f recommendation/kubernetes/Deployment-v3.yml
oc get pods -w
----


=== Wait for v3 to be deployed

Wait for those pods to show "2/2", the istio-proxy/envoy sidecar is part of that pod

[source,bash]
----
NAME                                  READY     STATUS    RESTARTS   AGE
customer-3600192384-fpljb             2/2       Running   0          17m
preference-243057078-8c5hz           2/2       Running   0          15m
recommendation-v1-60483540-9snd9     2/2       Running   0          12m
recommendation-v2-2815683430-vpx4p   2/2       Running   0          15s
recommendation-v3-7b445dd469-j6rkg   2/2       Running   0          2m
----

[source, terminal]
----
cd ${LAB_HOME}
----

[#istioegress]
== Istio-ize Egress

Be sure you do not have any previous destination rule nor virtual service installed.

Let's redirect all traffic to reccomendation:v3.

[source, bash,subs="+macros,+attributes"]
----
oc create -f istiofiles/lab7/destination-rule-recommendation-v1-v2-v3.yml

oc create -f istiofiles/lab7/virtual-service-recommendation-v3.yml
----

Then access to the service:



IMPORTANT: Since no Egress service entry has been registered to access an external site, the timeout error is thrown after 5 seconds of trying to access to the site.
.
[source, bash]
----
$ curl -m 5 ${CUSTOMER_URL}
----

Let's fix it by registering a service entry to allow access to `httpbin`.  IMPORTANT, THIS CHANGE may not be reflected immediately. This is normal behavior.

[source,bash,subs="+macros,+attributes"]
----
oc create -f istiofiles/lab7/service-entry-egress-httpbin.yml

oc get serviceentry

curl customer-tutorial.$(minishift ip).nip.io
customer => preference => Mon, 16 Jul 2018 12:03:38 GMT recommendation v3 from '7b445dd469-j6rkg': 1
----

or shell into the pod by getting its name and then using that name with oc exec

[source,bash]
----
oc exec -it $(oc get pods -o jsonpath="{.items[*].metadata.name}" -l app=recommendation,version=v3) -c recommendation /bin/bash

or

kubectl exec -it $(oc get pods -o jsonpath="{.items[*].metadata.name}" -l app=recommendation,version=v3) -c recommendation /bin/bash

curl http://now.httpbin.org

exit
----


=== Clean up

[source,bash]
----
oc delete -f istiofiles/lab7/service-entry-egress-httpbin.yml 
oc delete -f istiofiles/lab7/destination-rule-recommendation-v1-v2-v3.yml 
oc delete -f istiofiles/lab7/virtual-service-recommendation-v3.yml
----

